name: OpenAPI Diff
description: GitHub Action to determine changes in OpenAPI Schema
author: itsmycargo

inputs:
  base:
    description: Base OpenAPI specification
    required: true
  revision:
    description: Revised OpenAPI specification
    required: true
  github-token:
    description: GitHub Token as provided by secrets
    default: ${{ github.token }}
    required: true

outputs:
  state:
    description: State of the API changes
  verdict:
    description: Changes verdict
  changes:
    description: API Changes (as Markdown)

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base }}
    - ${{ inputs.revision }}
